workflows:
  ios-simulator:
    name: iOS Simulator Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod deintegrate
          pod install --repo-update
          cd ..

      - name: Build iOS app for simulator
        script: flutter build ios --simulator --no-codesign

    artifacts:
      - build/ios/iphonesimulator/**/*.app