workflows:
  ios-build:
    name: iOS build
    environment:
      flutter: stable
      xcode: 15.4
      cocoapods: default
    scripts:
      - name: Clean project
        script: |
          flutter clean
          flutter pub get
      - name: Clean CocoaPods cache
        script: |
          cd ios
          rm -rf Podfile.lock Pods
          pod repo update
          pod install --repo-update
          cd ..
      - name: Cleanup DerivedData
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
