// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNxszHjVNyUAFzu0qvUFoYAVNXzw0Dnek',
    appId: '1:399426774282:ios:4dc42fdad26ed642cd06f3',
    messagingSenderId: '399426774282',
    projectId: 'meditation-center-uae',
    storageBucket: 'meditation-center-uae.firebasestorage.app',
    androidClientId: '399426774282-p78ch2hn3uier9k8i6ts1t77568qhk0q.apps.googleusercontent.com',
    iosClientId: '399426774282-b1t2hlr1rensh86qdpg84gf5qagldt9h.apps.googleusercontent.com',
    iosBundleId: 'com.example.uaeMeditationCenter',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDXCx56seR31yyZ7my861qHL2LD3liVjs',
    appId: '1:399426774282:android:1d4972eb39180d1dcd06f3',
    messagingSenderId: '399426774282',
    projectId: 'meditation-center-uae',
    storageBucket: 'meditation-center-uae.firebasestorage.app',
  );

}